name: Setup Libraries
description: Runs autogen.sh in required folders
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt install gperf gettext autopoint
      shell: bash

    - name: Running autogen.sh in unibreak
      run: NOCONFIGURE=1 ./autogen.sh
      shell: bash
      working-directory: lib_ass/src/main/cpp/libass-cmake/src/unibreak

    - name: Running autogen.sh in fribidi
      run: NOCONFIGURE=1 ./autogen.sh
      shell: bash
      working-directory: lib_ass/src/main/cpp/libass-cmake/src/fribidi

    - name: Running autogen.sh in fontconfig
      run: NOCONFIGURE=1 ./autogen.sh
      shell: bash
      working-directory: lib_ass/src/main/cpp/libass-cmake/src/fontconfig

    - name: Running autogen.sh in ass
      run: ./autogen.sh
      shell: bash
      working-directory: lib_ass/src/main/cpp/libass-cmake/src/ass

    - name: Running buildconf.sh in expat
      run: ./buildconf.sh
      shell: bash
      working-directory: lib_ass/src/main/cpp/libass-cmake/src/expat/expat
