name: Publish to Maven Central Repository

on:
  release:
    types: [created]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-libraries

    - name: Publish to Maven Central Repository
      run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
